//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Onboarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Document_id { get; set; }
        public int Employee_id { get; set; }
        public string DocumentCode { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentDescription { get; set; }
        public string DocumentType { get; set; }
        public string Data { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
