//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Onboarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int PersonalInfo_id { get; set; }
        public int Employee_id { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string BloodGroup { get; set; }
        public string Address1 { get; set; }
        public string City1 { get; set; }
        public string State1 { get; set; }
        public string Country1 { get; set; }
        public string Address2 { get; set; }
        public string City2 { get; set; }
        public string State2 { get; set; }
        public string Country2 { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
