//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Onboarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousEmployment
    {
        public int PreviousEmployment_id { get; set; }
        public int Employee_id { get; set; }
        public string EmployerName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Designation { get; set; }
        public Nullable<long> Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
