//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Onboarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proof
    {
        public int Proof_id { get; set; }
        public int Employee_id { get; set; }
        public string ProofCode { get; set; }
        public string ProofName { get; set; }
        public string ProofId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
